---
- name: Install list of pkgs on remote machine
  hosts: web_node1
  
  vars:
    packages:
      - httpd
      - binutils
      - glibc
      - ksh
      - libaio
      - libXext
      - gcc
      - make
      - sysstat
      - unixODBC
      - mongodb
      - nodejs
      - grunt

  tasks:
    - name: Install "{{ item }}"
      yum: pkg={{ item }} state=installed
      become: yes
      with_items: "{{ packages }}"
      register: output

    - debug: msg="{{ item }}"
      with_items: "{{ output }}"       
...  
