---
- name: Install list of pkgs on remote machine
  hosts: web_node1
  
  vars:
    packages:
      - httpd
      - binutils
      - glibc
      - ksh
      - libaio
      - libXext
      - gcc
      - make
      - sysstat
      - unixODBC

  tasks:
    - name: Install "{{ item }}"
      yum: 
        name: "{{ packages }}"
        state: present
      become: yes
      register: output
    

    - debug: msg="{{ item }}"
      with_items: "{{ output.results}}"       
...  
